<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfiguracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfiguracionRepository extends EntityRepository
{
    public function obtener(){
        $dql='SELECT c.clave, c.valor FROM MainBundle:Configuracion c';
        return $this->getEntityManager()
            ->createQuery($dql)
            ->getResult();
    }
}
